### ISSUE TITLE
Discoverability of features

### ISSUE THREAD

**Issue by ivirshup** [scverse/genomic-features#6]
### Description of feature

How do we make it clear which:

* Annotation columns
* Filters
* Genomes

Are available to be used. `GenomicFeatures`/ `ensembldb` do this with a combination of functions for listing available features and pre-defined classes that make these available.

Examples include:

* Available columns: accessor functions like `transcripts`, `axons`
* Filters: `GeneIdFilter`, `CoordinateFilter` classes
* Genomes: `listEnsDbs`

Do we copy this design? The filter classes may be quite a lot of effort for our first draft.

-------

To implement:

- [x] Filters (`gf.filters` namespace + doc-site)
- [x] Annotation columns (`list_columns`, `list_tables`) (#22)
- [x] Genomes (`gf.ensembl.list_ensdb_annotations`) (#21)

**Comment by emdann** [comment]
MVP filter classes IMO would be:
- by gene biotype e.g. get all protein coding 
- by ensembl ID
- by gene name
- by chromosome 
- by genomic coordinates (any overlap in first instance, no filtering of gene starts/ends)

**Comment by ivirshup** [comment]
Idea: we can start with a partial set of filters, plus support for ibis expressions. We can then add these in steps.
